CREATE TABLE Drivers (DriverID INT PRIMARY KEY, Nome VARCHAR(100) NOT NULL, CNH VARCHAR(20) UNIQUE NOT NULL, Endereço VARCHAR(200), Contato VARCHAR(50));
GO
CREATE TABLE Clients (ClientID INT PRIMARY KEY, Nome VARCHAR(100) NOT NULL, Empresa VARCHAR(100), Endereço VARCHAR(200), Contato VARCHAR(50));
GO
CREATE TABLE Orders (OrderID INT PRIMARY KEY, ClientID INT NOT NULL, DriverID INT NOT NULL, DetalhesPedido VARCHAR(MAX), DataEntrega DATE, Status VARCHAR(50), FOREIGN KEY (ClientID) REFERENCES Clients(ClientID), FOREIGN KEY (DriverID) REFERENCES Drivers(DriverID));
GO